// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuAIguLdhh-1KoNeYbQt3esmggJJIwsws',
    appId: '1:182891626906:web:0fa9a9c0666693d66b3a23',
    messagingSenderId: '182891626906',
    projectId: 'mad-project-02',
    authDomain: 'mad-project-02.firebaseapp.com',
    storageBucket: 'mad-project-02.firebasestorage.app',
    measurementId: 'G-LKGT489SH1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOpSTEQNfDYCgEG8DaHJUcUXPV3T-8f3Q',
    appId: '1:182891626906:android:ead7b75767feca9a6b3a23',
    messagingSenderId: '182891626906',
    projectId: 'mad-project-02',
    storageBucket: 'mad-project-02.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_y5ta1jJWyQP0QWmC3Kiee4LaWc7GLy0',
    appId: '1:182891626906:ios:f879bdf64096bf966b3a23',
    messagingSenderId: '182891626906',
    projectId: 'mad-project-02',
    storageBucket: 'mad-project-02.firebasestorage.app',
    iosBundleId: 'com.example.vibzcheck',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_y5ta1jJWyQP0QWmC3Kiee4LaWc7GLy0',
    appId: '1:182891626906:ios:f879bdf64096bf966b3a23',
    messagingSenderId: '182891626906',
    projectId: 'mad-project-02',
    storageBucket: 'mad-project-02.firebasestorage.app',
    iosBundleId: 'com.example.vibzcheck',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAuAIguLdhh-1KoNeYbQt3esmggJJIwsws',
    appId: '1:182891626906:web:bb456a41a5f684cd6b3a23',
    messagingSenderId: '182891626906',
    projectId: 'mad-project-02',
    authDomain: 'mad-project-02.firebaseapp.com',
    storageBucket: 'mad-project-02.firebasestorage.app',
    measurementId: 'G-0036VFD76V',
  );
}
